package com.shouqi.mirror.gofunlocationservice.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shouqi.mirror.gofunlocationservice.dao.LocationBean;

import com.shouqi.mirror.gofunlocationservice.dao.LocationBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationBeanDaoConfig;

    private final LocationBeanDao locationBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationBeanDaoConfig = daoConfigMap.get(LocationBeanDao.class).clone();
        locationBeanDaoConfig.initIdentityScope(type);

        locationBeanDao = new LocationBeanDao(locationBeanDaoConfig, this);

        registerDao(LocationBean.class, locationBeanDao);
    }
    
    public void clear() {
        locationBeanDaoConfig.clearIdentityScope();
    }

    public LocationBeanDao getLocationBeanDao() {
        return locationBeanDao;
    }

}
