package com.shouqiev.mirror.launcher.fragment.map.util;

public class TestJson {
  public static final String orderJson = "{\n"
      + "    \"code\":200,\n"
      + "    \"desc\":\"OK\",\n"
      + "    \"modelData\":{\n"
      + "                \"orderId\":\"180117104428005XSL8RR1\",\n"
      + "                \"startTime\": 1514731289,\n"
      + "                \"duration\": 1000,\n"
      + "                \"distance\": 2000,\n"
      + "                \"takeParking\": {\n"
      + "                    \"parkingId\":\"eb8ef9ef-68a7-4b01-9b5a-c908829a8b96\",\n"
      + "                    \"name\":\"丽影广场停车场\",\n"
      + "                    \"latitude\": 31.540701,\n"
      + "                    \"longitude\": 120.445993,\n"
      + "                    \"image\":[\n"
      + "                        \"http://img.shouqiev.com/group1/M00/90/C8/ChJpo1vZYhmAPujvAAAJNigsI2k153.bmp\",\n"
      + "                        \"http://img.shouqiev.com/group1/M00/F7/7E/ChJppFuI6KOAU-fgAAF3YwqvDcg496.jpg\"\n"
      + "                    ]\n"
      + "                },\n"
      + "                \"returnParking\": {\n"
      + "                    \"parkingId\":\"eb8ef9ef-68a7-4b01-9b5a-c908829a8b96\",\n"
      + "                    \"name\":\"丽影广场停车场\",\n"
      + "                    \"latitude\": 31.540701,\n"
      + "                    \"longitude\": 120.445993,\n"
      + "                    \"image\":[\n"
      + "                        \"http://img.shouqiev.com/group1/M00/90/C8/ChJpo1vZYhmAPujvAAAJNigsI2k153.bmp\",\n"
      + "                        \"http://img.shouqiev.com/group1/M00/F7/7E/ChJppFuI6KOAU-fgAAF3YwqvDcg496.jpg\"\n"
      + "                    ]\n"
      + "                }\n"
      + "    }\n"
      + "}";

  public static final String parkingJson = "{\n"
      + "    \"code\":200,\n"
      + "    \"desc\":\"OK\",\n"
      + "    \"modelData\":{\n"
      + "        \"list\" : [\n"
      + "               {\n"
      + "                    \"parkingId\":\"eb8ef9ef-68a7-4b01-9b5a-c908829a8b96\",\n"
      + "                    \"name\":\"丽影广场停车场\",\n"
      + "                    \"latitude\": 31.540701,\n"
      + "                    \"longitude\": 120.445993,\n"
      + "                    \"image\":[\n"
      + "                        \"http://img.shouqiev.com/group1/M00/90/C8/ChJpo1vZYhmAPujvAAAJNigsI2k153.bmp\",\n"
      + "                        \"http://img.shouqiev.com/group1/M00/F7/7E/ChJppFuI6KOAU-fgAAF3YwqvDcg496.jpg\"\n"
      + "                    ]\n"
      + "                },\n"
      + "                {\n"
      + "                    \"parkingId\":\"eb8ef9ef-68a7-4b01-9b5a-c908829a8b96\",\n"
      + "                    \"name\":\"丽影广场停车场\",\n"
      + "                    \"latitude\": 31.540701,\n"
      + "                    \"longitude\": 120.445993,\n"
      + "                    \"image\":[\n"
      + "                        \"http://img.shouqiev.com/group1/M00/90/C8/ChJpo1vZYhmAPujvAAAJNigsI2k153.bmp\",\n"
      + "                        \"http://img.shouqiev.com/group1/M00/F7/7E/ChJppFuI6KOAU-fgAAF3YwqvDcg496.jpg\"\n"
      + "                    ]\n"
      + "                }\n"
      + "            ]\n"
      + "    }\n"
      + "}";
  public static final String otaJson = "\n"
      + "{\n"
      + "    \"code\":200,\n"
      + "    \"desc\":\"OK\",\n"
      + "    \"modelData\":{\n"
      + "                \"status\":\"1\",\n"
      + "                \"downloadPath\": \"https://img.shouqiev.com/group2/M00/52/4B/ChJpdFvlDVGAIYNZAAAI9EtFSAM810.txt\",\n"
      + "                \"appVersion\":\"100\"\n"
      + "                \"description\": \"\"\n"
      + "    }\n"
      + "}";
  public static final String loginJson = "\n"
      + "{\n"
      + "    \"code\":200,\n"
      + "    \"desc\":\"OK\",\n"
      + "    \"modelData\":{\n"
      + "        \"token\" : \"13uiasdfhjl123ekhsai2\",\n"
      + "        \"orderId\" : \"181231224129844XOCO3X2\"\n"
      + "    }\n"
      + "  \n"
      + "}";
}
