package com.shouqiev.mirror.launcher.fragment.map.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shouqiev.mirror.launcher.fragment.map.dao.ParkingBean;
import com.shouqiev.mirror.launcher.model.EnvironmentDetail;

import com.shouqiev.mirror.launcher.fragment.map.dao.ParkingBeanDao;
import com.shouqiev.mirror.launcher.fragment.map.dao.EnvironmentDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig parkingBeanDaoConfig;
    private final DaoConfig environmentDetailDaoConfig;

    private final ParkingBeanDao parkingBeanDao;
    private final EnvironmentDetailDao environmentDetailDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        parkingBeanDaoConfig = daoConfigMap.get(ParkingBeanDao.class).clone();
        parkingBeanDaoConfig.initIdentityScope(type);

        environmentDetailDaoConfig = daoConfigMap.get(EnvironmentDetailDao.class).clone();
        environmentDetailDaoConfig.initIdentityScope(type);

        parkingBeanDao = new ParkingBeanDao(parkingBeanDaoConfig, this);
        environmentDetailDao = new EnvironmentDetailDao(environmentDetailDaoConfig, this);

        registerDao(ParkingBean.class, parkingBeanDao);
        registerDao(EnvironmentDetail.class, environmentDetailDao);
    }
    
    public void clear() {
        parkingBeanDaoConfig.clearIdentityScope();
        environmentDetailDaoConfig.clearIdentityScope();
    }

    public ParkingBeanDao getParkingBeanDao() {
        return parkingBeanDao;
    }

    public EnvironmentDetailDao getEnvironmentDetailDao() {
        return environmentDetailDao;
    }

}
